### ISSUE TITLE
Build fails on Win 10 Python 3.6.4

### ISSUE THREAD

**Issue by dza6549** [james-owen-ryan/expressionist#6]
Hi James

I found Expressionist via Reddit. The vocals on Sheldon are outstanding. I've been playing with AWS Polly - how are you coding the tempo of the speech - in particular the pause/timing between words - yours sound remarkably realistic.

If you can provide guidance on how I might get Expressionist to work on Win 10 I would be most grateful

I'm trying to install Expressionist on Win 10 - Python 3.6.4 Anaconda but get the following messages:

D:\...path..\expressionist>pip install -r requirements.txt
Collecting appnope==0.1.0 (from -r requirements.txt (line 1))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading appnope-0.1.0-py2.py3-none-any.whl
Collecting decorator==4.0.6 (from -r requirements.txt (line 2))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading decorator-4.0.6-py2.py3-none-any.whl
Collecting Flask==0.10.1 (from -r requirements.txt (line 3))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 552kB 2.6MB/s
Collecting gnureadline==6.3.3 (from -r requirements.txt (line 4))
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading gnureadline-6.3.3.tar.gz (2.5MB)
    100% |████████████████████████████████| 2.5MB 438kB/s
    Complete output from command python setup.py egg_info:
    Error: this module is not meant to work on Windows (try pyreadline instead)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\.. path ..\AppData\Local\Temp\pip-build-fvj59xhe\gnureadline\
Cache entry deserialization failed, entry ignored

Thanks

**Comment by possibly** [comment]
Hey @dza6549!

Hm, I will have more time to look at this throughout the week, but at first glance the problem seems to be that the `gnureadline` dependency is not supported on Windows. The console suggests using `pyreadline`.

Try replacing the `requirements.txt` file with this:

```
appnope==0.1.0
decorator==4.0.6
Flask==0.10.1
ipython==4.1.1
ipython-genutils==0.1.0
itsdangerous==0.24
Jinja2==2.8
jsontree==0.4.3
marisa-trie==0.7.4
MarkupSafe==0.23
path.py==10.4
pexpect==3.3
pickleshare==0.5
pyreadline==2.1
simplegeneric==0.8.1
traitlets==4.1.0
Werkzeug==0.11.3
```

And then `pip install -r requirements.txt`.

This new file replaces `gnureadline` with `pyreadline`. I tested this replacement really briefly on my mac and nothing blew up, so maybe give this a try.

**Comment by dza6549** [comment]
OK great thanks James I'll give that a shot. Shall report back. Cheers

**Comment by dza6549** [comment]
Hi James
No luck unfortunately "Pexpect is intended for UNIX-like operating systems."
Got it running on the Mac though.
Cheers
